# Links

forums: https://hypixel.net
store: https://store.hypixel.net
discordserverlink: https://discord.gg/hypixel

# Challenges

challenge-1: Your first challenge
challenge-2: Your second challenge
challenge-3: Your third challenge
challenge-4: Your fourth challenge
challenge-5: Your fifth challenge
challenge-6: Your sixth challenge
challenge-7: Your seventh challenge
challenge-8: Your eighth challenge
challenge-9: Your ninth challenge
challenge-10: Your tenth challenge
