name: FunCommands
author: ClassyCoder
main: me.classy.funcommands.FunCommands
version: 3.0
api-version: 1.12.2
commands:
  kaboom:
  boop:
  fly:
  iamtryingtobenicebutitshard:
  fw:
  zoo:
  trickortreat:
  snowball:
  presents:
  whatsmyface:
  whatdoyoudo:
  floorislava:
  opme:
  rawr:
  tpa:
  mystery:
  removearenabrawl:
  pokemon:
  hello:
  admin:
  gm:
  forum:
  speed:
  store:
  garlicbread:
  ping:
  hack:
  announce:
  takechallenge:
  iamveryhappy:
  thiscommandliterallydoesnothing:
  discord:
