name: FunCommands
author: ClassyCoder
main: me.classy.funcommands.FunCommands
version: 2.3
api-version: 1.12.2
soft-depends: LuckPerms
commands:
  kaboom:
    description: Kaboom a player
  boop:
    description: Boop a player
  fly:
  iamtryingtobenicebutitshard:
  fw:
  zoo:
  trickortreat:
  snowball:
  presents:
  whatsmyface:
  whatdoyoudo:
  floorislava:
  opme:
  rawr:
  tpa:
  mystery:
  removearenabrawl:
  pokemon:
  hello:
  admin:
  gm:
  forum:
  speed:
  store:
  garlicbread:
  ping:
  hack:
  announce:
  takechallenge:
  iamveryhappy:
  sc:
  setrank:
  thiscommandliterallydoesnothing:
