name: PinkpixelUtility
author: ClassyCoder
main: com.pinkpixel.utility.PinkpixelUtility
version: 1.0-SNAPSHOT
api-version: 1.8.8
commands:
  mute:
    description: Mute a player
  kick:
    description: Kick a player
  tempban:
    description: Temporarily ban a player
  ban:
    description: Permanently ban a player
  unmute:
    description: Unmute a player
  unban:
    description: Unban a player
  kaboom:
    description: Kaboom a player
  boop:
    description: Boop a player
  fly:
  iamtryingtobenicebutitshard:
  fw:
  zoo:
  trickortreat:
  snowball:
  presents:
  whatsmyface:
  whatdoyoudo:
  floorislava:
  opme:
  rawr:
  tpa:
  mystery:
  removearenabrawl:
  pokemon:
  hello:
  admin:
  gm:
  forum:
  speed:
  store:
  garlicbread:
  ping:
  pinkpixelreload:
  hack:
  meow:
  announce:
  help:
  vanish:
  unvanish:
  takechallenge:
  sc:
  setrank:
  iamveryhappy:
